### ISSUE TITLE
Precision align?

### ISSUE THREAD

**Issue by www516717402** [OutBreak-hui/Yolov5-PP-LCNet#1]
Have you test precision align with paddlecls in imagenet? ConvBNLayer is different with [pp-lcnet](https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.3/ppcls/arch/backbone/legendary_models/pp_lcnet.py) in your repo.

**Comment by OutBreak-hui** [comment]
> 您是否测试过与 imagenet 中的 paddlecls 对齐的精度？ConvBNLayer 与repo 中的[pp-lcnet](https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.3/ppcls/arch/backbone/legendary_models/pp_lcnet.py)不同。

Thanks for your reminder, You mean that bn and hardswish are missing? I will modify it soon，I have not tested precision align with paddlecls in imagenet , but this works for yolov5. Comparing with yolov5s in my business data, the number of parameters and Gflops are reduced by half under the condition of the same accuracy.

**Comment by www516717402** [comment]
Thank you for reply. I already align output between torch and paddle.
